---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "192.168.33.40"}]
    run_list:
      - recipe[wonderstuff::default]
    attributes:

